dist: trusty

language: node_js

node_js:
  - "7.4.0"

matrix:
  fast_finish: true

before_install:
  - npm -g i greenkeeper-lockfile@1

install:
  - npm i

before_script:
  - greenkeeper-lockfile-update

script:
  - npm run lint

after_script:
  - greenkeeper-lockfile-upload
  - if [ -n "${TRAVIS_TAG}" ]; then npm run github-release; fi
